resources:
- ../base
- env-ops-configmap.yaml
- r63d7f27/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r63d7f27/revision-patch.yaml
  target:
    kind: Service
- path: r63d7f27/routing-patch.yaml
  target:
    kind: Service